name: "auto-approval"
description: "Automatically approves PRs by admin users"
author: "menny"
inputs:
  token:
    description: "GitHub Token"
    required: true
  allowed_users:
    description: "Which users can be auto-approved. Comma separated list."
    required: true
  review_as:
    description: "Approver login."
    required: true
runs:
  using: "composite"
  entrypoint: /bin/bash
  args:
    - bazel
    - run
    - //js/auto_approval:auto_approval
branding:
  icon: 'git-pull-request'
  color: green
