---
name: 'Deploy Request'
description: 'Request deployment of the IMA and all AddOns'
inputs:
  gh_user:
    description: 'GitHub API username'
    required: true
  gh_token:
    description: 'GitHub API token'
    required: true
  repo_owner:
    description: 'Repository owner username'
    default: 'AnySoftKeyboard'
  repo_name:
    description: 'Repository name'
    default: 'AnySoftKeyboard'
  sha:
    description: 'Commit SHA to deploy'
    default: 'HEAD'
  refname:
    description: 'Branch name to release'
    required: true
  deploy_mode:
    description: 'What to deploy'
    required: true
runs:
  using: "composite"
  steps:
    - uses: bazel-contrib/setup-bazel@0.15.0
      with:
        bazelisk-cache: true
        disk-cache: ${{ github.workflow }}
        repository-cache: true
    - name: Request IME Deployment
      run: |
        bazel run //js/github_deployments -- deploy \
          --api-username="${{ inputs.gh_user }}" \
          --token="${{ inputs.gh_token }}" \
          --owner="${{ inputs.repo_owner }}" \
          --repo="${{ inputs.repo_name }}" \
          --sha="${{ inputs.sha }}" \
          --refname="${{ inputs.refname }}" \
          --shardName=ime \
          --deployMode="${{ inputs.deploy_mode }}"
    - name: Request add-ons Deployment
      run: |
        bazel run //js/github_deployments -- deploy \
          --api-username="${{ inputs.gh_user }}" \
          --token="${{ inputs.gh_token }}" \
          --owner="${{ inputs.repo_owner }}" \
          --repo="${{ inputs.repo_name }}" \
          --sha="${{ inputs.sha }}" \
          --refname="${{ inputs.refname }}" \
          --shardName=addons \
          --deployMode="${{ inputs.deploy_mode }}"
