---
name: deployment-promote
on:
  schedule:
    - cron: '04 04 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  TERM: dumb
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
jobs:
  promote:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        refname: [main, release-branch-addons-v5.1-r1]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          ref: ${{ matrix.refname }}
      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: request-scheduled-promote
        run: |-
          bazel run //js/github_deployments -- deploy \
            --api-username=${{ secrets.BOT_MASTER_RW_GITHUB_USERNAME }} \
            --token=${{ secrets.BOT_MASTER_RW_GITHUB_TOKEN }} \
            --owner=${{ github.repository_owner }} \
            --repo=AnySoftKeyboard \
            --sha=HEAD \
            --refname=${{ matrix.refname }} \
            --step=1
