---
name: packs-lists
on:
  push:
    branches:
      - main
    paths:
      - 'addons/**'
      - '.github/workflows/packs_md_update.yml'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  TERM: dumb
  TMPDIR: "/tmp"
jobs:
  packs-md-update:
    runs-on: ubuntu-24.04
    container: ghcr.io/menny/android:1.21.2
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.BOT_MASTER_RW_GITHUB_TOKEN }}
      - name: setup
        run: ./scripts/ci/ci_setup.sh
      - name: update packs list
        run: ./gradlew :addons:languages:generatePacksMarkDown :addons:themes:generatePacksMarkDown :addons:quicktexts:generatePacksMarkDown
      - name: Create pull request
        id: create_pr_packs_md
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          token: ${{ secrets.BOT_MASTER_RW_GITHUB_TOKEN }}
          commit-message: 'Automated Packs List Update'
          title: 'Automated Packs List Update'
          committer: 'Polyglot <ask@evendanan.net>'
          author: 'Polyglot <ask@evendanan.net>'
          body: 'Generated from latest _main_ addons packages.'
          team-reviewers: add-on-maintainers
          branch: 'bot-pr/packs-list-update'
          delete-branch: true
      - name: Generate PACKS.yml
        if: steps.create_pr_packs_md.outputs.pull_request_number != '' && steps.create_pr_packs_md.outputs.pull_request_operation != 'closed'
        run: ./gradlew :addons:generatePacksYaml
      - name: Checkout AnySoftKeyboard.github.io repository
        if: steps.create_pr_packs_md.outputs.pull_request_number != '' && steps.create_pr_packs_md.outputs.pull_request_operation != 'closed'
        uses: actions/checkout@v4
        with:
          repository: AnySoftKeyboard/AnySoftKeyboard.github.io
          path: anysoftkeyboard.github.io
          token: ${{ secrets.BOT_MASTER_RW_GITHUB_TOKEN }}
      - name: Commit and Push PACKS.yml to .github.io repo
        if: steps.create_pr_packs_md.outputs.pull_request_number != '' && steps.create_pr_packs_md.outputs.pull_request_operation != 'closed'
        run: |
          mv ./PACKS.yml ./anysoftkeyboard.github.io/PACKS.yml
          cd ./anysoftkeyboard.github.io
          git config user.name "Polyglot"
          git config user.email "ask@evendanan.net"
          git checkout -B packs-list-update
          git add PACKS.yml
          # Only commit if PACKS.yml has changed
          if ! git diff --staged --quiet; then
            git commit -m "Automated PACKS.yml update from main repository"
            git push --force origin packs-list-update
          else
            echo "No changes to PACKS.yml to commit."
          fi
